// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZLQ2Fos0kIWxqJMckNM97ngo5S3q9-j8',
    appId: '1:305195102130:web:22cff2b3ebceb72973feab',
    messagingSenderId: '305195102130',
    projectId: 'shopapp-24aaa',
    authDomain: 'shopapp-24aaa.firebaseapp.com',
    storageBucket: 'shopapp-24aaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vCqzpjNuNJwz1V2-l9VTmBA-8EcTybs',
    appId: '1:305195102130:android:e763faee39b82bc973feab',
    messagingSenderId: '305195102130',
    projectId: 'shopapp-24aaa',
    storageBucket: 'shopapp-24aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClS3Xix9CCZ-bzIQHa0tCMJMPkJySrfvc',
    appId: '1:305195102130:ios:5fe88860b1688fd373feab',
    messagingSenderId: '305195102130',
    projectId: 'shopapp-24aaa',
    storageBucket: 'shopapp-24aaa.appspot.com',
    iosBundleId: 'com.example.shopAppFlutterUdemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClS3Xix9CCZ-bzIQHa0tCMJMPkJySrfvc',
    appId: '1:305195102130:ios:cc338e0ac5a3ab0573feab',
    messagingSenderId: '305195102130',
    projectId: 'shopapp-24aaa',
    storageBucket: 'shopapp-24aaa.appspot.com',
    iosBundleId: 'com.example.shopAppFlutterUdemy.RunnerTests',
  );
}
